// FOR DEVELOPMENT PURPOSE ONLY!
const ACCESS_TOKEN =
  "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMjAwNDg0NEBzaXN3YS51bS5lZHUubXkiLCJpYXQiOjE3MzI5NzU1MzEsImV4cCI6MTczMjk3NzMzMX0.A1LHnUlyfrKnIGM7N3M05wgfpuFmyFpKyJGyNeL5VoeYQ9u5amYZUwyyylItmw1WLoHKVBuf_xOuRSfxrXbcLg";

const GOOGLE_MAPS_API_KEY = "AIzaSyBapQKkarYUNa-F4NAXcrWwJHJNeajYNuY";

export { ACCESS_TOKEN, GOOGLE_MAPS_API_KEY };
