// FOR DEVELOPMENT PURPOSE ONLY!
const ACCESS_TOKEN =
  "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMjAwNDg0NEBzaXN3YS51bS5lZHUubXkiLCJpYXQiOjE3MzI5NjI4NjUsImV4cCI6MTczMjk2NDY2NX0.bdQNeiZSsXwuYQl96MCJ1fAmDBKxvHJ8g87oRAtJjC3Gl068du9q3Xbln1mWEyWqkhO0eIV50zcdMyfTI_mW9Q";

const GOOGLE_MAPS_API_KEY = "AIzaSyBapQKkarYUNa-F4NAXcrWwJHJNeajYNuY";

export { ACCESS_TOKEN, GOOGLE_MAPS_API_KEY };
